In [1]:
import sys

print(sys.executable)

c:\Users\gouda\OneDrive\Desktop\Job-Market-Intelligence\.venv\Scripts\python.exe

In [2]:
import pandas as pd

file_path = "../data/indian-job-market-dataset-2025.xlsx"

df = pd.read_excel(file_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 97929
Columns: 17

In [3]:
df = pd.read_excel("../data/indian-job-market-dataset-2025.xlsx")

print(df.shape)
print(df.columns.tolist())

(97929, 17)
['title', 'jobId', 'currency', 'jobUploaded', 'companyName', 'tagsAndSkills', 'experience', 'salary', 'location', 'companyId', 'ReviewsCount', 'AggregateRating', 'jobDescription', 'minimumSalary', 'maximumSalary', 'minimumExperience', 'maximumExperience']

In [4]:
df.head()

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              97929 non-null  str
 1   jobId              97929 non-null  int64
 2   currency           97929 non-null  str
 3   jobUploaded        97929 non-null  str
 4   companyName        97925 non-null  str
 5   tagsAndSkills      97358 non-null  str
 6   experience         95824 non-null  str
 7   salary             97929 non-null  str
 8   location           97929 non-null  str
 9   companyId          97929 non-null  int64
 10  ReviewsCount       62677 non-null  float64
 11  AggregateRating    62677 non-null  float64
 12  jobDescription     97929 non-null  str
 13  minimumSalary      97358 non-null  float64
 14  maximumSalary      97358 non-null  float64
 15  minimumExperience  97358 non-null  float64
 16  maximumExperience  97358 non-null  float64
dtypes: float64(6), int64(2), str(9)
memory usage: 12.7 MB

In [6]:
missing = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": (df.isna().mean() * 100).round(2)
})

missing.sort_values("missing_percent", ascending=False)

                   missing_count  missing_percent
AggregateRating            35252            36.00
ReviewsCount               35252            36.00
experience                  2105             2.15
minimumSalary                571             0.58
tagsAndSkills                571             0.58
maximumExperience            571             0.58
maximumSalary                571             0.58
minimumExperience            571             0.58
title                          0             0.00
location                       0             0.00
salary                         0             0.00
jobUploaded                    0             0.00
companyName                    4             0.00
currency                       0             0.00
jobId                          0             0.00
jobDescription                 0             0.00
companyId                      0             0.00

In [7]:
df["currency"].value_counts(dropna=False)

currency
INR    97800
USD      129
Name: count, dtype: int64

In [8]:
df[
    [
        "title",
        "currency",
        "salary",
        "minimumSalary",
        "maximumSalary"
    ]
].dropna(
    subset=["minimumSalary", "maximumSalary"]
).head(20)

,title,currency,salary,minimumSalary,maximumSalary
0,Sr. HR Recruiter (NON IT),INR,2-4 Lacs PA,200000.0,400000.0
1,Fire And Safety Officer,INR,3-5 Lacs PA,300000.0,500000.0
2,Opening For Performance Marketing - Chennai,INR,Not disclosed,0.0,0.0
3,Medical Billing Executive,INR,"70,000-2 Lacs PA",70000.0,200000.0
4,Senior Group Product Manager - CNS Therapy,INR,8-18 Lacs PA,800000.0,1800000.0
5,Senior Accountant,INR,3.5-6 Lacs PA,350000.0,600000.0
6,Maintenance Technician,INR,Not disclosed,0.0,0.0
7,Officer/Engineer Technical,INR,Not disclosed,0.0,0.0
8,Officer- Technical Lab,INR,Not disclosed,0.0,0.0
9,Site Reliability Engineer,INR,Not disclosed,0.0,0.0
10,Hiring For Voice & Chat Process,INR,"50,000-1.75 Lacs PA",50000.0,175000.0
11,Talent Acquisition Professional,INR,Not disclosed,0.0,0.0
12,Hiring For Chat Process,INR,"50,000-2.5 Lacs PA",50000.0,250000.0
13,HR Recruiter | Regional Recruiter | Jaipur,INR,Not disclosed,0.0,0.0
14,MEP Billing Engineer (Jaipur),INR,Not disclosed,0.0,0.0
15,JOB For MALE |Fraud Prevention Credit card || ...,INR,3-4.5 Lacs PA,300000.0,450000.0
16,Pole Deployment Engineer (Off Role),INR,2-4.5 Lacs PA,200000.0,450000.0
17,"Senior Engineer-Mechanical (Planning/Billing),...",INR,6-9 Lacs PA,600000.0,900000.0
18,Design Engineer-Mechanical/Civil (Fabrication ...,INR,4.5-6 Lacs PA,450000.0,600000.0
19,Design Manager-Mechanical/Civil (Fabrication D...,INR,6-12 Lacs PA,600000.0,1200000.0

In [9]:
print("Total jobs:", len(df))

print(
    "Jobs with salary range:",
    ((df["minimumSalary"] > 0) & (df["maximumSalary"] > 0)).sum()
)

print(
    "Jobs with undisclosed/zero salary:",
    ((df["minimumSalary"] == 0) | (df["maximumSalary"] == 0)).sum()
)

print(
    "\nSalary coverage:",
    round(
        ((df["minimumSalary"] > 0) &
         (df["maximumSalary"] > 0)).mean() * 100,
        2
    ),
    "%"
)

Total jobs: 97929
Jobs with salary range: 33229
Jobs with undisclosed/zero salary: 64129

Salary coverage: 33.93 %

In [10]:
df["tagsAndSkills"].head(10)

0    Communication,Manpower,Staffing,Convincing Pow...
1    Safety Officer Activities,Fire Protection,Fire...
2    Performance Marketing,User Acquisition,growth ...
3    Fluent English,Spoken English,Good English Com...
4    Product Marketing,CNS,Product Management,Nephr...
5    Tds Filing,ITR,Gst Filing,Balance Sheet Finali...
6    Booth,Conveyor,Special Process,Utility Mainten...
7    M.S Office,SAP,Computer Skills,MS Office,Techn...
8     SAP,Laboratory Knowledge,Microsoft,Technical,Lab
9    Sre,Azure Devops,Monitoring Tools,Site,Site Re...
Name: tagsAndSkills, dtype: str

In [11]:
import pandas as pd
import numpy as np

file_path = "../data/indian-job-market-dataset-2025.xlsx"

df = pd.read_excel(file_path)

print("Raw shape:", df.shape)

Raw shape: (97929, 17)

In [12]:
df = df.rename(columns={
    "jobId": "job_id",
    "companyName": "company_name",
    "jobUploaded": "job_uploaded",
    "tagsAndSkills": "tags_and_skills",
    "companyId": "company_id",
    "ReviewsCount": "reviews_count",
    "AggregateRating": "aggregate_rating",
    "jobDescription": "job_description",
    "minimumSalary": "minimum_salary",
    "maximumSalary": "maximum_salary",
    "minimumExperience": "minimum_experience",
    "maximumExperience": "maximum_experience"
})

df.columns.tolist()

['title',
 'job_id',
 'currency',
 'job_uploaded',
 'company_name',
 'tags_and_skills',
 'experience',
 'salary',
 'location',
 'company_id',
 'reviews_count',
 'aggregate_rating',
 'job_description',
 'minimum_salary',
 'maximum_salary',
 'minimum_experience',
 'maximum_experience']

In [13]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate job IDs:", df["job_id"].duplicated().sum())

Duplicate rows: 247
Duplicate job IDs: 250

In [14]:
df = df.drop_duplicates(
    subset="job_id",
    keep="first"
).copy()

print("After deduplication:", df.shape)

After deduplication: (97679, 17)

In [15]:
text_columns = [
    "title",
    "company_name",
    "currency",
    "location",
    "tags_and_skills",
    "experience",
    "salary",
    "job_description"
]

for col in text_columns:
    df[col] = (
        df[col]
        .astype("string")
        .str.strip()
    )

In [16]:
for col in text_columns:
    df[col] = df[col].replace(
        ["", "nan", "None", "NA", "N/A"],
        pd.NA
    )

In [17]:
import re

def normalize_title(title):

    if pd.isna(title):
        return pd.NA

    title = str(title).lower().strip()

    # Replace punctuation with spaces
    title = re.sub(r"[^a-z0-9+#./& -]", " ", title)

    # Common abbreviations
    replacements = {
        r"\bsr\b": "senior",
        r"\bsr\.\b": "senior",
        r"\bjr\b": "junior",
        r"\bjr\.\b": "junior",
        r"\bdev\b": "developer",
        r"\beng\b": "engineer",
        r"\bmgmt\b": "management",
        r"\bdept\b": "department",
        r"\bassoc\b": "associate",
        r"\bvp\b": "vice president",
        r"\bdir\b": "director"
    }

    for pattern, replacement in replacements.items():
        title = re.sub(
            pattern,
            replacement,
            title
        )

    # Normalize whitespace
    title = re.sub(r"\s+", " ", title).strip()

    return title.title()

In [18]:
df["normalized_title"] = df["title"].apply(
    normalize_title
)

In [19]:
df[
    ["title", "normalized_title"]
].head(30)

,title,normalized_title
0,Sr. HR Recruiter (NON IT),Senior. Hr Recruiter Non It
1,Fire And Safety Officer,Fire And Safety Officer
2,Opening For Performance Marketing - Chennai,Opening For Performance Marketing - Chennai
3,Medical Billing Executive,Medical Billing Executive
4,Senior Group Product Manager - CNS Therapy,Senior Group Product Manager - Cns Therapy
5,Senior Accountant,Senior Accountant
6,Maintenance Technician,Maintenance Technician
7,Officer/Engineer Technical,Officer/Engineer Technical
8,Officer- Technical Lab,Officer- Technical Lab
9,Site Reliability Engineer,Site Reliability Engineer
10,Hiring For Voice & Chat Process,Hiring For Voice & Chat Process
11,Talent Acquisition Professional,Talent Acquisition Professional
12,Hiring For Chat Process,Hiring For Chat Process
13,HR Recruiter | Regional Recruiter | Jaipur,Hr Recruiter Regional Recruiter Jaipur
14,MEP Billing Engineer (Jaipur),Mep Billing Engineer Jaipur
15,JOB For MALE |Fraud Prevention Credit card || ...,Job For Male Fraud Prevention Credit Card Poon...
16,Pole Deployment Engineer (Off Role),Pole Deployment Engineer Off Role
17,"Senior Engineer-Mechanical (Planning/Billing),...",Senior Engineer-Mechanical Planning/Billing Va...
18,Design Engineer-Mechanical/Civil (Fabrication ...,Design Engineer-Mechanical/Civil Fabrication D...
19,Design Manager-Mechanical/Civil (Fabrication D...,Design Manager-Mechanical/Civil Fabrication Dr...
20,Cardiologist For Nalgonda & Vijayawada,Cardiologist For Nalgonda & Vijayawada
21,International Voice Process || Customer Care &...,International Voice Process Customer Care & Up...
22,Assistant Manager- Bakery,Assistant Manager- Bakery
23,Walk In Drive @Noida | Quality Analyst | TELUS...,Walk In Drive Noida Quality Analyst Telus Digital
24,4LPA CTC For Email Chat Backend & Non Voice Pr...,4Lpa Ctc For Email Chat Backend & Non Voice Pr...
25,Embryologist,Embryologist
26,Billing Engineer,Billing Engineer
27,ATM Implementation - Software Engineer / Senio...,Atm Implementation - Software Engineer / Senio...
28,Software Engineer Implementation,Software Engineer Implementation
29,Relationship Manager - Key Partnership Group,Relationship Manager - Key Partnership Group

In [20]:
salary_columns = [
    "minimum_salary",
    "maximum_salary"
]

for col in salary_columns:

    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

    df.loc[
        df[col] <= 0,
        col
    ] = np.nan

In [21]:
df[
    ["salary", "minimum_salary", "maximum_salary"]
].head(20)

                 salary  minimum_salary  maximum_salary
0           2-4 Lacs PA        200000.0        400000.0
1           3-5 Lacs PA        300000.0        500000.0
2         Not disclosed             NaN             NaN
3      70,000-2 Lacs PA         70000.0        200000.0
4          8-18 Lacs PA        800000.0       1800000.0
5         3.5-6 Lacs PA        350000.0        600000.0
6         Not disclosed             NaN             NaN
7         Not disclosed             NaN             NaN
8         Not disclosed             NaN             NaN
9         Not disclosed             NaN             NaN
10  50,000-1.75 Lacs PA         50000.0        175000.0
11        Not disclosed             NaN             NaN
12   50,000-2.5 Lacs PA         50000.0        250000.0
13        Not disclosed             NaN             NaN
14        Not disclosed             NaN             NaN
15        3-4.5 Lacs PA        300000.0        450000.0
16        2-4.5 Lacs PA        200000.0        450000.0
17          6-9 Lacs PA        600000.0        900000.0
18        4.5-6 Lacs PA        450000.0        600000.0
19         6-12 Lacs PA        600000.0       1200000.0

In [22]:
df["salary_midpoint"] = (
    df["minimum_salary"] +
    df["maximum_salary"]
) / 2

In [23]:
df["salary_midpoint"].describe()

count    3.313600e+04
mean     7.573380e+05
std      1.026111e+06
min      7.860000e+02
25%      2.875000e+05
50%      4.250000e+05
75%      8.250000e+05
max      8.250000e+07
Name: salary_midpoint, dtype: float64

In [24]:
df["currency"].value_counts(dropna=False)

currency
INR    97550
USD      129
Name: count, dtype: Int64

In [25]:
experience_columns = [
    "minimum_experience",
    "maximum_experience"
]

for col in experience_columns:

    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

In [26]:
df["experience_midpoint"] = (
    df["minimum_experience"] +
    df["maximum_experience"]
) / 2

In [27]:
df["job_uploaded"] = pd.to_datetime(
    df["job_uploaded"],
    errors="coerce"
)

C:\Users\gouda\AppData\Local\Temp\ipykernel_25872\1186035220.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["job_uploaded"] = pd.to_datetime(

In [28]:
print(df["job_uploaded"].dtype)

print(
    df["job_uploaded"].min(),
    "→",
    df["job_uploaded"].max()
)

datetime64[s]
NaT → NaT

In [29]:
df["posting_year"] = (
    df["job_uploaded"].dt.year
)

df["posting_month"] = (
    df["job_uploaded"].dt.to_period("M")
    .astype(str)
)

In [30]:
df["location"] = (
    df["location"]
    .astype("string")
    .str.strip()
    .str.replace(
        r"\s+",
        " ",
        regex=True
    )
)

In [31]:
df["location"].value_counts().head(30)

location
Bengaluru                                 16783
Hyderabad                                  7657
Pune                                       6096
Chennai                                    4418
Gurugram                                   4226
Mumbai                                     4149
Noida                                      2688
Remote                                     1952
Ahmedabad                                  1721
Navi Mumbai                                1451
Kolkata                                    1047
Hyderabad, Chennai, Bengaluru              1037
Hybrid - Bengaluru                          943
Jaipur                                      815
Coimbatore                                  618
Hybrid - Hyderabad                          575
Kochi                                       526
Vadodara                                    526
Hybrid - Pune                               478
Thane                                       408
Surat                                       407
Nagpur                                      406
Mumbai Suburban                             378
Lucknow                                     332
Chandigarh                                  297
Mohali                                      295
Chennai, Bengaluru                          284
Hyderabad, Bengaluru                        279
Hybrid - Hyderabad, Chennai, Bengaluru      269
Faridabad                                   268
Name: count, dtype: Int64

In [32]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing values:")
print(
    df.isna().sum()
    .sort_values(ascending=False)
)

Rows: 97679
Columns: 22

Missing values:
job_uploaded           97679
posting_month          97679
posting_year           97679
minimum_salary         64543
salary_midpoint        64543
maximum_salary         64535
aggregate_rating       35163
reviews_count          35163
experience              2102
minimum_experience       571
tags_and_skills          571
maximum_experience       571
experience_midpoint      571
company_name               4
currency                   0
job_id                     0
title                      0
company_id                 0
job_description            0
salary                     0
location                   0
normalized_title           0
dtype: int64

In [33]:
print("\nDuplicate job IDs:")
print(df["job_id"].duplicated().sum())

Duplicate job IDs:
0

In [34]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-25.0.1-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-25.0.1-cp314-cp314-win_amd64.whl (28.6 MB)
   ---------------------------------------- 0.0/28.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/28.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/28.6 MB ? eta -:--:--
   - -------------------------------------- 0.8/28.6 MB 1.4 MB/s eta 0:00:20
   - -------------------------------------- 1.0/28.6 MB 1.5 MB/s eta 0:00:19
   - -------------------------------------- 1.3/28.6 MB 1.5 MB/s eta 0:00:18
   -- ------------------------------------- 1.8/28.6 MB 1.6 MB/s eta 0:00:17
   --- ------------------------------------ 2.4/28.6 MB 1.7 MB/s eta 0:00:16
   ---- ----------------------------------- 2.9/28.6 MB 1.9 MB/s eta 0:00:14
   ---- ----------------------------------- 3.4/28.6 MB 2.0 MB/s eta 0:00:13
   ----- ---------------------------------- 3.9/28.6 MB 2.0 MB/s eta 0:00:13
   ------ --------------------------------- 4.5/28.6 MB 2.1 MB/s eta 0:00:12
   ------ --------------------------------- 5.0/28.6 MB 2.2 MB/s eta 0:00:11
   ------- -------------------------------- 5.2/28.6 MB 2.2 MB/s eta 0:00:11
   ------- -------------------------------- 5.5/28.6 MB 2.1 MB/s eta 0:00:11
   -------- ------------------------------- 5.8/28.6 MB 2.0 MB/s eta 0:00:12
   -------- ------------------------------- 6.0/28.6 MB 2.0 MB/s eta 0:00:12
   -------- ------------------------------- 6.3/28.6 MB 1.9 MB/s eta 0:00:12
   --------- ------------------------------ 6.6/28.6 MB 1.9 MB/s eta 0:00:12
   --------- ------------------------------ 6.8/28.6 MB 1.8 MB/s eta 0:00:12
   --------- ------------------------------ 7.1/28.6 MB 1.8 MB/s eta 0:00:12
   ---------- ----------------------------- 7.6/28.6 MB 1.8 MB/s eta 0:00:12
   ---------- ----------------------------- 7.9/28.6 MB 1.8 MB/s eta 0:00:12
   ----------- ---------------------------- 8.4/28.6 MB 1.8 MB/s eta 0:00:12
   ------------ --------------------------- 8.7/28.6 MB 1.8 MB/s eta 0:00:11
   ------------ --------------------------- 8.9/28.6 MB 1.8 MB/s eta 0:00:11
   ------------- -------------------------- 9.4/28.6 MB 1.8 MB/s eta 0:00:11
   ------------- -------------------------- 9.7/28.6 MB 1.8 MB/s eta 0:00:11
   ------------- -------------------------- 10.0/28.6 MB 1.8 MB/s eta 0:00:11
   -------------- ------------------------- 10.5/28.6 MB 1.8 MB/s eta 0:00:11
   --------------- ------------------------ 11.0/28.6 MB 1.8 MB/s eta 0:00:10
   ---------------- ----------------------- 11.5/28.6 MB 1.8 MB/s eta 0:00:10
   ---------------- ----------------------- 12.1/28.6 MB 1.9 MB/s eta 0:00:09
   ----------------- ---------------------- 12.6/28.6 MB 1.9 MB/s eta 0:00:09
   ------------------ --------------------- 13.1/28.6 MB 1.9 MB/s eta 0:00:09
   ------------------- -------------------- 13.9/28.6 MB 1.9 MB/s eta 0:00:08
   -------------------- ------------------- 14.4/28.6 MB 2.0 MB/s eta 0:00:08
   -------------------- ------------------- 14.9/28.6 MB 2.0 MB/s eta 0:00:07
   --------------------- ------------------ 15.7/28.6 MB 2.0 MB/s eta 0:00:07
   ---------------------- ----------------- 16.3/28.6 MB 2.1 MB/s eta 0:00:07
   ----------------------- ---------------- 16.8/28.6 MB 2.1 MB/s eta 0:00:06
   ------------------------ --------------- 17.3/28.6 MB 2.1 MB/s eta 0:00:06
   ------------------------- -------------- 18.1/28.6 MB 2.1 MB/s eta 0:00:05
   -------------------------- ------------- 18.9/28.6 MB 2.1 MB/s eta 0:00:05
   --------------------------- ------------ 19.4/28.6 MB 2.2 MB/s eta 0:00:05
   ---------------------------- ----------- 20.2/28.6 MB 2.2 MB/s eta 0:00:04
   ----------------------------- ---------- 21.0/28.6 MB 2.2 MB/s eta 0:00:04
   ------------------------------ --------- 22.0/28.6 MB 2.3 MB/s eta 0:00:03
   ------------------------------- -------- 22.8/28.6 MB 2.3 MB/s eta 0:00:03
   -------------------------------- ------- 23.6/28.6 MB 2.4 MB/s eta 0:00:03
   ---------------------------------- ----- 24.6/28.6 MB 2.4 MB/s eta 0:00:02
   ----------------------------------- ---- 25.7/28.6 MB 2.5 MB/s eta 0:00:02
   ------------------------------------ --- 26.2/28.6 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 27.0/28.6 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 27.8/28.6 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  28.6/28.6 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 28.6/28.6 MB 2.5 MB/s  0:00:11
Installing collected packages: pyarrow
Successfully installed pyarrow-25.0.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
df.to_csv(
    "../data/cleaned_jobs.csv",
    index=False
)

print("Saved cleaned dataset.")

Saved cleaned dataset.

In [37]:
import os

print(
    "File exists:",
    os.path.exists("../data/cleaned_jobs.csv")
)

print(
    "Rows saved:",
    len(pd.read_csv("../data/cleaned_jobs.csv"))
)

File exists: True
Rows saved: 97679